Refactor smart comment parsing
graphile/crystal pull request #1908
Opened 2024-01-07 17:38 UTC by diesal11

2024-01-08 09:28 UTC, benjie commented
The problem with this is it means there’s no way to start a comment with an `@`; for example `@benjie indicated CITEXT is appropriate here`. Currently the double newline is used as a “the description follows” break.

2024-01-08 13:26 UTC, diesal11 commented
Ah, I knew i would be overlooking something....

I could update it to support breaking an `@` with a `\` on a given line. I.E. `\@benjie indicated CITEXT is appropriate here` ?

But that would also be a breaking change. The simpler solution may just be to be explicit the effect of a double newline into the docs?

2024-01-08 14:46 UTC, benjie commented
Yes; please feel free to add that as part of the smart comments specification if it's not already clear. There should be an "edit this page" link on the relevant page of the docs.

I'd also be open to a PR that output a warning for comments that start with an `@`, though there would need to be a way to explicitly mark it as deliberate (e.g. `\@`; but if you add that then you also need to add `\\`... And it would change the format for existing comments (though this is unlikely to have been hit). And then are you escaping everything or just the first character? Also putting `\` inside an `E` string in Postgres is not ideal:

```
comment on thing is
  E'@omit create\n@name Whatever\n\n\\@benjie says this is fine';
```
)

So yeah... Probably docs only for now.

2024-02-06 15:34 UTC, benjie requested changes
Awesome; thanks!

2024-02-06 15:34 UTC, benjie commented on postgraphile/website/postgraphile/smart-comments.md
> +newline will be parsed & will be treated as part of the description.
```suggestion
Note that adding two newlines in a row separates the smart tags section from the
descriptive prose. Content after two newlines will not be parsed for smart tags
even if it starts with an `@` character.
```

2024-02-06 15:34 UTC, benjie approved these changes

2024-02-06 15:35 UTC, benjie requested changes

2024-02-06 15:35 UTC, benjie commented on postgraphile/website/postgraphile/smart-comments.md
> +
```suggestion
even if it starts with an `@` character.

For example:

```

2024-02-06 15:35 UTC, benjie commented on postgraphile/website/postgraphile/smart-comments.md
> +Results in the following JSON tags object:
```suggestion
results in the following JSON tags object:
```

2024-02-06 15:36 UTC, benjie approved these changes

2024-02-06 15:44 UTC, merged