Clarify amber preset behavior in nodeId documentation
graphile/crystal pull request #2002
Opened 2024-03-22 19:20 UTC by jcgsville

## Description

Added a section to nodeId/relay portion of documentation to clarify that the amber preset also overrides postgraphile's default.

Also included a plugin to revert that, though I can remove that if we think it is too verbose

Following up on discord thread: https://discord.com/channels/489127045289476126/489717163280826374/1220790554334334996

## Performance impact

None

## Security impact

None

## Checklist

- [x] My code matches the project's code style and `yarn lint:fix` passes.

2024-03-22 20:19 UTC, benjie requested changes
Effectively only the _legacy_ preset uses `nodeId` by default; amber is our base (primary) preset, it's just not very stable/documented yet.

Please edit the first paragraph to remove the `nodeId` variant talk, and then add a section at the bottom about `id` clashing with row IDs (`rowId`) and give two options:

1. use the Relay preset, which will remove `rowId` entirely (but is still experimental), or
2. use V4 preset or a plugin like the one you indicate to rename `id` -> `nodeId` so that the table field `id` does not clash.

I.e. basically invert the article. Thanks! :heart:

2024-03-23 00:27 UTC, jcgsville commented
Took a pass on updating the entire article to not be so nodeId centric. Hope it's useful

2024-03-25 11:19 UTC, benjie requested changes
Really good! Just a few changes needed (which hopefully I can apply...)

2024-03-25 11:19 UTC, benjie commented on postgraphile/website/postgraphile/node-id.md
> +2. You can use a V4 preset that mimics the behavior and settings of Postgraphile V4
```suggestion
2. You can use a V4 preset that mimics the behavior and settings of PostGraphile V4
```

2024-03-25 11:19 UTC, benjie commented on postgraphile/website/postgraphile/node-id.md
> +    name: 'RevertToNodeIdPlugin',
```suggestion
const IdToNodeIdPlugin: GraphileConfig.Plugin = {
    name: 'IdToNodeIdPlugin',
```

2024-03-25 11:19 UTC, benjie commented on postgraphile/website/postgraphile/node-id.md
> +            attribute: (previous: any, options: any, details: any) => {
Theoretically these should be automatically typed for you, you should not need to declare them as any!

```suggestion
            attribute(previous, options, details) {
```

2024-03-25 11:19 UTC, benjie commented on postgraphile/website/postgraphile/node-id.md
> +  dataIdFromObject: (object) => object.id || null,
```suggestion
  dataIdFromObject: (object) => object.id || null,
  // Or if you renamed 'id' to 'nodeId' then:
  //   dataIdFromObject: (object) => object.nodeId || null,
```

2024-03-25 11:20 UTC, benjie approved these changes
Great! I think the only remaining issue is the text hasn't been formatted with Prettier (I noticed 4-space indentation in the code block)

2024-03-25 11:21 UTC, benjie commented on postgraphile/website/postgraphile/node-id.md
> +            nodeIdFieldName: (): string => 'nodeId',
```suggestion
            nodeIdFieldName(){ return 'nodeId'; },
```

2024-03-25 15:31 UTC, merged

2024-03-30 21:41 UTC, jcgsville commented
Thanks for the tweaks and for getting it merged. Looking forward to it being reflected on the site 😄 Cheers!

2024-03-31 10:08 UTC, benjie commented
🙌 Just a heads up it’s going to be a while before it ships because a lot of the website currently reflects ` main ` which has some unreleased major changes and more to come before release.